### ISSUE TITLE
Tatarigoroshi-hen (3rd chapter) no "credits"

### ISSUE THREAD

**Issue by copyread** [MyLegGuy/Higurashi-Vita#15]
At the end of Tatarigoroshi-hen, when the "credits" scroll, there's just a black screen on Vita with the music playing. Here's how it should roughly look (spoilers):

https://youtu.be/TekKoTPD9HI?t=1758

I am aware that's probably out of the capabilities of VNDS, but you could probably make an optional extension of the format, as you're the sole person working on it currently. :)

**Comment by MyLegGuy** [comment]
thank you for the bug report.
it is some sort of libvita2d issue being unable to load the massive panning texture.
hopefully i can fix this if i try

**Comment by MyLegGuy** [comment]
i actually worried about this section a lot. i tested it a bunch of times on my pc build of this engine, but i never suspected the vita would fail to load the image making all my pc tests worthless.
this section uses a giant panning texture.
the size is 640x4736. according to libvita2d, no texture can be more than GXM_TEX_MAX_SIZE (4096) in width or height.
so the texture fails to load.

because i can't fix the code to let it load that giant image, my only option was to edit HigurashiVitaConverter to shrink the image a bit more. I released v1.7.3 for that with a fix.

if you want to have the fix without converting the entire game again, copy the contents of this zip file to your StreamingAssets/CG folder for ch3.
[shrink.zip](https://github.com/MyLegGuy/Higurashi-Vita/files/4707157/shrink.zip)
