### ISSUE TITLE
Any chance Meakashi can/will be fixed for non-PS3 patch players?

### ISSUE THREAD

**Issue by Theswweet** [MyLegGuy/Higurashi-Vita#17]
I'm not sure how interested you are in fixing the port to be able to run stock, but here's the first crash point for ch5 if you don't use the PS3 patch.

https://imgur.com/a/DTzjXaM

Line it crashes right after on Meakashi Day 1, plus the error it spits out. FWIW I skipped through ch6 up to Day 2-2 and ran into the same error - maybe fixing this will help the rest of the game be playable?

**Comment by Theswweet** [comment]
Quick update - I found out what seems to be causing these crashes, as well as a potential workaround. It happens whenever the game calls CallScript(), and if you simply copy the script contents from the called text file and replace this function with that, the game will work normally - unpatched.

I have no idea why this works with the PS3 patch, but not here normally.

In this case, the crash occurs because the game tries to load the eyecatch from a separate file, which doesn't work as loading a separate file while the engine is already within a file seems broken.

I'm not sure, but is it possible that you can code something into the converter to do this manually?

**Comment by MyLegGuy** [comment]
if you're willing to test the game and report bugs in a way that doesn't spoil the game for me, i'm willing to work with you to get it to work. 
hopefully only a few code changes will be required.

this particular bug seems to be with the "#include" written at the top of the eyecatch script.
i think it'll probably work fine if those are removed?
i added a little change to the game converter to remove them.
you can either reconvert the entire game ([HigurashiVitaConverter-06-19-2020.zip](https://github.com/MyLegGuy/Higurashi-Vita/files/4807421/HigurashiVitaConverter-06-19-2020.zip)) or just remove the "#include ..." lines manually from the script files.
the files that have "#include" in them are:
```	&endroll_sion.txt
	&eyecamp.txt
	&eye.txt
	&toketu2.txt
	&toketu.txt
```
also, my engine clears all the text when CallScript is used.
it looks like CallScript is just used for these transitions, so that shouldn't be a problem.

**Comment by Theswweet** [comment]
Just tested myself - it does appear to work! Thanks! I've already converted my files for 6 and 7, but apparently I had forgot to remove a callscript() function from the staffroom in 5 - so I was able to test if just removing the #include lines works. It does.
