### ISSUE TITLE
Overlapping BGM in Higurashi Answer Chapters when stock

### ISSUE THREAD

**Issue by Theswweet** [MyLegGuy/Higurashi-Vita#18]
Separate from #17, but I discovered the discrepancy during further testing. For whatever reason, the usage of the FadeOutBGM() function is flipped in ch5 onwards. In, say, Onikakushi - it would be called like FadeOutBGM( 1, 1000, TRUE ) - with the initial number denoting one of the 4 audio tracks, 0-3 - while in Meakashi onwards it is called as FadeOutBGM( 1, 0, FALSE ). This won't crash the game or anything, but instead of the intended behavior of the function, well, fading out audio - it'll leave audio tracks looping. This leads to inappropriate music for certain situations, and tracks that were meant to be cleared overshadowing other ones (such as the music for the opening credits at the end of Meakashi Day 1)

There is a workaround - if you find+replace to set the functions to be called as they would've been in Hou, everything works on Vita as it would on PC. Maybe this can also be handled during conversion? I don't know if this is an issue with the PS3 patch, but it certainly is if you don't have it installed.

**Comment by MyLegGuy** [comment]
the second number is the amount of time it takes to fadeout.
i think in the second case, it's just an instant fadeout. (which is weird because there's a StopBGM command already available, no need for FadeOut with time 0.)
and because of how I programmed it on the vita, a fadeout that takes 0 time will either crash the program or have an infinetly long fadeout.
here is a build that hopefully fixes that bug:
https://github.com/MyLegGuy/Higurashi-Vita/releases/download/v2.9.4.1/Higurashi-Vita-v2.9.4.2-BETA.vpk
i sure hope it doesn't instantly crash or anything horrible.

**Comment by Theswweet** [comment]
I reconverted Ch5 using the newest version of the tool you posted on the other ticket, and tested the first part of Ch5 - the newest version works like a charm! With these two fixed, that should be the main issues preventing Answer Arcs from working. I'll update you if I run into any problems in the others.
