### ISSUE TITLE
Inconsistent Crashes Linked to usage of SetSpeedOfMessage() in Wata_ep1 and Onik_15_02

### ISSUE THREAD

**Issue by Theswweet** [MyLegGuy/Higurashi-Vita#19]
Sorry for yet another issue ticket - but this is something that both me (reading on Vita) and my friend (reading on 3DS) have run into. I ran into it in Chapter 1 on the 15-2 script file, and seems to be linked to some sort of bug with SetSpeedOfMessage() and a similar situation in the Chapter 2 Ep-1 script file. I don't truly know if it's the function that causes the crash - but it's the one thing that they both seem to have in common. This crash is inconsistent - sometimes you'll be lucky and it won't happen, but it happens often enough to be notable. Sometimes it won't be these exact lines that cause the crashes, but 9/10 they are - the other 1/10 it crashes it'll be shortly after these lines. I really don't get it - maybe you will?

Onikakushi 15-2

> //「あはははは。監督は監督さんだよ。!s200あははははははははははははははははは!sd。＠
> 	OutputLine(NULL, "「あはははは。監督は監督さんだよ。",
> 		   NULL, "\"Ahahaha. The Manager is the manager.", Line_ContinueAfterTyping);
> 	SetSpeedOfMessage( TRUE, 0, );
> 
> 	OutputLine(NULL, "あははははははははははははははははは。」",
> 		   NULL, " Ahahahahahahahahahahahahahahahahaha.\"", Line_WaitForInput);
> 
> 	SetSpeedOfMessage( FALSE, 0, );
> 	OutputLineAll(NULL, "\n", Line_ContinueAfterTyping);

Watanagashi Ep-1

> //「け、!w1000......けけけ...!s100けけけけけけけけけけけけけけけけけ!sd...＠　間に合った...＠...間に合った...＠　...!s100くけけけけけけけけけけけけけけけけけけ!sd！！！＠
> 	OutputLine(NULL, "「け、",
> 		   NULL, "\"Hee.....", Line_ContinueAfterTyping);
> 
> 	SetValidityOfInput( FALSE );
> 	Wait( 1000 );
> 	SetValidityOfInput( TRUE );
> 
> 	OutputLine(NULL, "……けけけ…",
> 		   NULL, " heeheehee...", Line_ContinueAfterTyping);
> //!s100
> 	SetSpeedOfMessage( TRUE, 120, );
> 
> 	OutputLine(NULL, "けけけけけけけけけけけけけけけけけ",
> 		   NULL, " heeheeheeheeheeheeheeheeheeheeheeheeheehee", Line_ContinueAfterTyping);
> //!sd
> 	SetSpeedOfMessage( FALSE, 0, );

FWIW I didn't run into any crashes in Chapter 3 or Chapter 4, so those seem to be fine on that end!

**Comment by MyLegGuy** [comment]
thank you for the detailed report.
here is the fix:
https://github.com/MyLegGuy/Higurashi-Vita/releases/download/v2.9.4.1/Higurashi-Vita-v2.9.4.2-BETA-2.vpk
i was able to reproduce the crash and test the fix myself, so you don't need to test it yourself if you don't want to.
if you're interested, the actual reason for the crash was a bug with the code that handles super long words. And maniacal laugher without any spaces qualifies as a single giant word.

i'm amazed that there is a single human using the 3ds version.
that version hasn't been updated in over two years. i don't even have a 3ds development environment set up.
the engine used to have *even more* problems with long lines, so that explains why the 3ds is crashing too.
i'm sorry to say that i will likely never update it again.
it would be a lot of work and i've only ever heard from one other person who'd like it updated. And on top of that, 3ds homebrew development is a nightmare compared to vita.

**Comment by Theswweet** [comment]
Thanks! If I run into any crashes resembling the ones in earlier chapters I'll update - but for now I've got other things to worry about, haha. Something tells me that Chapter 6 is going to be a problem child.
