### ISSUE TITLE
Suggestion: Implement StartShakingOfWindow(), StartShakingOfAllObjects() functions

### ISSUE THREAD

**Issue by Theswweet** [MyLegGuy/Higurashi-Vita#25]
Not really a bug, but these functions begin to see much more use in the latter chapters of the story. It's by no means a priority, but when you have the chance - it would be good to implement it.

**Comment by Theswweet** [comment]
Woops - it's *only* in the Answer Arcs, but it's very prevalent!

```
StartShakingOfWindow( 248, 40, 0, 2, 5*2, FALSE );
StartShakingOfAllObjects( 248, 40, 0, 2, 5*2, TRUE );
```
Just one example of how it's used.

**Comment by MyLegGuy** [comment]
I've implemented the Answer Arcs' shake screen commands.
(I'll do ShakeScreen and ShakeScreenSx, which are for games 1-4, later because their syntax is a bit different.)
I am pleased by the accuracy of my implementation.
https://github.com/MyLegGuy/Higurashi-Vita/releases/download/v2.9.4.1/Higurashi-Vita-v2.9.5-BETA-7.vpk
This version also implements ChangeBustshot.

I won't be able to work on this much more until next week. Bug reports are still appreciated though.

**Comment by Theswweet** [comment]
Awesome! I'll check this out tomorrow. Thanks for your work over the last 2 weeks!

**Comment by Theswweet** [comment]
Sorry for the later than expected response, but I sanity checked, and this is working on my end as well!

**Comment by MyLegGuy** [comment]
nice
