### ISSUE TITLE
White filter is oddly formatted, doesn't take up the whole screen/doesn't cull at the end of the background

### ISSUE THREAD

**Issue by Theswweet** [MyLegGuy/Higurashi-Vita#27]
I kept forgetting to post this, since it's minor, but the white filter that I believe you implemented has some odd formatting atm.

https://i.imgur.com/wpFnufd.png

Not sure if your recent commits dedicated to culling stuff out of bounds might've fixed it.

**Comment by MyLegGuy** [comment]
Thank you. I kept forgetting about this one.
Fixed, it'll be in whatever the next build I post.
For regular textbox mode, it'll work as you expect.
If the user sets the text to start at the edge of the screen instead of at the edge of the background ("textbox: full" in the settings) then I decided to keep the filter going across the entire screen.
