### ISSUE TITLE
Minor branching path in Chapter 7

### ISSUE THREAD

**Issue by Theswweet** [MyLegGuy/Higurashi-Vita#28]
Minagoroshi has a minor choice early on, for Day 2-1. At the end you're given a choice - and the intended outcome is that, while nothing changes, there's slight variations in dialog. Intended behavior is that depending on the choice the player will either read Day 2-1a or Day 2-1b, and then move on to Day 2-2. Of course, with the current way that preset files work - it'll just read both back to back.

Not a major issue, but one worth noting.

**Comment by MyLegGuy** [comment]
I'm assuming there's some sort of `select` command for the choice, but then what happens?
Does the game do the branching from within the script file, or does the script file end before using CallScript on another?
If it *does* do the branching from within the script file, the code likely looks something like this:
```
Item = {}

if(GetGlobalFlag("GLanguage")==1)
then
Item[1] = "choice1";
Item[2] = "choice2";
else
Item[1] = "japanesechoice1";
Item[2] = "japanesechoice2";
end

//	InitializeSelectedItem();
Select( 2, Item );

if(LoadValueFromLocalWork("SelectResult")==0)
then
CallScript( "day2_1a" );
end

if(LoadValueFromLocalWork("SelectResult")==1)
then
CallScript( "day2_1b" );
end
```
(the above code is how it would look in the converted script files. if you're looking at the raw files, some keywords will be different.)

if the branching *is* done from within the script file, then things should already work. Right?
Just remove 2-1a and 2-1b from the preset file because they're launched from 2-1 and we'll be good.

-------

However, because you're posting this issue, I assume that the branching is not done from within day 2-1's script.
If 2-1 ends before the branching, then the branching is likely done in `flow.txt` script.
`flow.txt` controls the order of the scripts. My engine never reads `flow.txt`, I use preset files to get the order instead. Was that a stupid decision I made a couple of years ago? Yes, but it's done now.

-------
Assuming the script ends before the branching:
-------
So, instead, let's program in the branching ourselves.
HigurashiVitaConverter already allows me to put custom script files into the converted games, so let's make a modified version of day 2-1's script.
That way, we can just copy the branching from flow.txt into the actual script.
First, open the **converted** version of 2-1's script. Make sure it's the converted version, not the raw version from the original game.
Next, go to the bottom of the script. Then go up a bit, go to the line *before* the line with `end` written on it.
(The `select` command will probably be one of the last things in the script because that's where the branch is. If the `select` command is earlier in the script and only branches at the end of the script, that's fine too.)
You need to add code to do the branching. Looking at the above example, you likely only need to add this:
```
if(LoadValueFromLocalWork("SelectResult")==0)
then
CallScript( "day2_1a" );
end

if(LoadValueFromLocalWork("SelectResult")==1)
then
CallScript( "day2_1b" );
end
```
Obviously, change "day2_1a" and "day2_1b" to the actual script names.
Once you've done that modification, please test it to make sure it works.
Then, remove day2-1a and 2-1b from the preset file. I'm assuming you know how to do this. If not, ask.
Finally, when the script file is working, upload the entire script file. I will add it to HigurashiVitaConverter.

**Comment by Theswweet** [comment]
I adjusted the script file, as you asked. It worked seamlessly - I've also adjusted the preset file, accordingly.

Assuming that the rest goes well, it seems Minagoroshi may be free of any other issues, besides the ones I've already posted.

[_mina_002_1.txt](https://github.com/MyLegGuy/Higurashi-Vita/files/4817000/_mina_002_1.txt)
