### ISSUE TITLE
Crash after "It'll shake much less than that boat did" (Umineko)

### ISSUE THREAD

**Issue by retosik** [MyLegGuy/Higurashi-Vita#3]
Game crashes after "It'll shake much less than that boat did" text, like ~15 minutes into the game. Issue is reproducible (happens every time after this line)
https://webmshare.com/play/wyarK
https://drive.google.com/file/d/1Mzqt6YuTatB1QkfpXeGxovSPiaqMmPPC/view?usp=sharing (psp2dmp)

**Comment by MyLegGuy** [comment]
Can't reproduce it on my side.

If you downloaded this pre-conveted for VNDS, could you link the files for me so we both have the exact same?

Also, could you install this (https://github.com/MyLegGuy/Higurashi-Vita/releases/download/v2.5/Higurashi-dev-2.5.0.vpk) VPK and upload the new psp2dmp?

**Comment by retosik** [comment]
>Also, could you install this (https://github.com/MyLegGuy/Higurashi-Vita/releases/download/v2.5/Higurashi-dev-2.5.0.vpk) VPK and upload the new psp2dmp?

Done.
https://drive.google.com/file/d/1F43rqi80NCVxXZsMqofy8dA-3576IG6D/view?usp=sharing

>If you downloaded this pre-conveted for VNDS, could you link the files for me so we both have the exact same?

I think I downloaded the question arcs from... somewhere, converted it with [anonl's VNDS Umineko Converter](http://www.mediafire.com/download/02fab1m49x0qi1x/UminekoConverter-1.5.1-win32.7z) and then with your converter (VNDSVitaConverter_v0.1 with ffmpeg installed). So it isn't the perfect version, but VNDS Android plays it fine ([proofs lol](https://i.imgur.com/pSS2UE0.png)) (same version but before VNDSVitaConverter_v0.1 step ofc)
Anyway, this is the version which I am using with your player:
https://mega.nz/#!xhpC2CIB!gsNxXROlal1Gtu7wo3gDQAEjjxFpIw1YLD8CSCKAEKk

**Comment by MyLegGuy** [comment]
Thank you. I'm able to reproduce it now and have been working on it.
It took me a while, but I finally have an idea on how to fix the bug. If I'm lucky, I may be able to completely fix it tomorrow.

MyLegGuy's Blog:
--
It crashes because it fails to load jgtuv.png.
It fails to load jgtuv.png because it is a 308x425 image.
This is not my fault, it's the fault of the graphics code, libvita2d.
Because I didn't write libvita2d, I can't fix the image loading code, so I need a workaround.
I noticed that loading a 308x425 JPG image works, so I wrote code to make all the images JPG.
Then I saw that JPG doesn't support transparent backgrounds.
So then I was stumped. I even considered deleting the discussion thread and acting like the VNDS feature was never a thing.
But then, I got an idea.
First, I figure out some constant images dimensions that are guaranteed to work. 
Then, I use the game converter to round the images' dimensions up to the nearest safe dimensions. The image will not be scaled, though.
This way, libvita2d will have no excuse not to load the images I throw at it. 
This is the only solution other than fixing libvita2d. Big transparent portions of an image shouldn't take that much space because of compression. 
Phew, crisis averted.

**Comment by MyLegGuy** [comment]
Okay, try the [game converter v1.1](https://github.com/MyLegGuy/VNDSVitaConverter/releases).

What to do to prevent having to convert all the AAC audio again:
* If you're on Windows, just temporarily rename "ffmpeg.exe" to something else. Or just don't put "ffmpeg.exe" there at the one place.
* If you're on Linux, run the program with "mono VNDSConverter.exe <folder path> -ffmpeg off"
* Convert the VNDS game again.
* Move all the audio files from your old converted game folder to the new converted game folder.
* If you don't want to transfer too much to your Vita, you can just overwrite the "CGAlt" of the old game folder with the one from the new game folder.

**Comment by retosik** [comment]
but my audio's in OGG t_t
I'll just do the whole conversion anyway, I'm going out for a while (I'll let you know if it worked in 5 hours)

**Comment by retosik** [comment]
Went faster than expected. Works now. Great work!

https://i.imgur.com/euSviJT.png

**Comment by MyLegGuy** [comment]
Good to hear.
