### ISSUE TITLE
Any way to run on Windows?

### ISSUE THREAD

**Issue by ishani-rgb** [MyLegGuy/Higurashi-Vita#36]
This really isnt an issue or anything like that, and probably is a stupid question, but is there any way to build an executable for windows?

Ive been doing some work on VNDS and this seems ti be the best version of it available. I assume itll be possible through mingw and gcc but Im not sure.

Thanks in advance.

**Comment by MyLegGuy** [comment]
finally ready:
https://github.com/MyLegGuy/Higurashi-Vita/releases/download/v3.0.2/Higurashi-Windows-v3.0.2-test.zip
* i only lightly tested it because i dont use windows, so hopefully it works fine.
* to change the window size, edit "run-big.bat" using a text editor and then run the program by clicking that file.
* you mentioned you're working on vnds stuff. higurashi vita reorganizes vnds games a bit with its stupid [converter](https://github.com/MyLegGuy/VNDSVitaConverter). The changes aren't very drastic though, just unzipping and folder renaming.

**Comment by lochana-Dineko** [comment]
Thanks a lot! I really didn't expect it to be ready so soon! Thank you again.

**Comment by ishani-rgb** [comment]
Sorry for the late response. Its working very well. Its nice that the isembeded.txt thing also works on desktop. Its nice to use if you want to run only one game.
A nifty vn engine.
