### ISSUE TITLE
Add option to change default game directory

### ISSUE THREAD

**Issue by kayblis** [MyLegGuy/Higurashi-Vita#38]
Wondering if it would be possible to let the user choose their own directory for storing vns. I use SD2VITA and make use of both uma0 and ux0 partitions, and I want to store my vns in uma0 instead of the default directory in ux0.

**Comment by MyLegGuy** [comment]
> I want to store my vns in uma0 instead of the default directory in ux0.

If `uma0:data/HIGURASHI` exists, it will automatically be used instead of the one in `ux0`.

In this new beta build, I've added the ability for the user to specifically choose `ux0` or `uma0` instead of having it be automatic.
https://github.com/MyLegGuy/Higurashi-Vita/releases/download/v3.0.2/Higurashi-Vita-v3.0.3-BETA-2.vpk
This allows you to use `ux0` when `uma0` also exists.
The new setting is listed in the new settings menu.
